#!/usr/bin/env node
// Selects the branding profile the site ships with. The public deployment runs 'neutral', which
// carries no society logo, name, attribution or registry identity. 'ase' turns the full
// American Society of Echocardiography / ImageGuideEcho Registry identity back on.
// Run: node scripts/set-brand.mjs ase|neutral   (then rebuild: gen-registry, bundle-single)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const PROFILES = ['neutral', 'ase'];
const want = (process.argv[2] || '').toLowerCase();
if (!PROFILES.includes(want)) {
  console.error(`usage: node scripts/set-brand.mjs <${PROFILES.join('|')}>`);
  process.exit(1);
}
const src = path.join(root, 'config', `brand.${want}.json`);
const brand = JSON.parse(fs.readFileSync(src, 'utf8'));
if (brand.profile !== want) throw new Error(`profile mismatch in ${src}`);

fs.writeFileSync(
  path.join(root, 'data', 'brand.js'),
  `// Generated by scripts/set-brand.mjs — do not edit by hand.\n` +
  `// Active branding profile: ${want}. Switch with: node scripts/set-brand.mjs ${PROFILES.join('|')}\n` +
  `window.AIECHO_BRAND = ${JSON.stringify(brand, null, 1)};\n`,
);
console.log(`brand profile: ${want}${brand.org ? ` (${brand.org.short})` : ' (no organisation identity)'}`);
